# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # 获取源码
    - name: checkout
      uses: actions/checkout@v2
    # 复制代码到服务器
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_TOKEN }}
        REMOTE_HOST: '182.254.205.45'
        REMOTE_USER: 'root'
        SOURCE: ''
        TARGET: '/home/actions'
    # ssh连接服务器，执行命令
    - name: start server
      uses: appleboy/ssh-action@master
      with:
        host: '182.254.205.45'
        username: 'root'
        key: ${{ secrets.SERVER_TOKEN }}
        script: |
          cd /home/actions
          touch success.txt
      
